apiVersion: v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    tier: frontend 
    app: nginx-deployk
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-test
          image: nginx
  selector:
    matchLabels:
      app: myapp
    
